### ISSUE TITLE
Remove jQuery

### ISSUE THREAD

**Issue by raultomescu** [RaulTsc/TorrentVideo#1]
jQuery is used only for some AJAX requests. Can and should be removed and replaced with vanilla JS XmlHTTP Requests or a more light-weight framework

**Comment by yordis** [comment]
@RaulTsc use [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)

**Comment by raultomescu** [comment]
This one should be closed in https://github.com/RaulTsc/TorrentVideo/commit/eb1f2b1d8fd0ce3d6bb702c7712c18e29fd71447

**Comment by raultomescu** [comment]
Thanks @yordis

**Comment by yordis** [comment]
@RaulTsc I didn't do anything lol, just the remainder :laughing:

**Comment by raultomescu** [comment]
Was not aware that fetch existed :)

**Comment by yordis** [comment]
@RaulTsc https://github.com/RaulTsc/TorrentVideo/commit/eb1f2b1d8fd0ce3d6bb702c7712c18e29fd71447#commitcomment-15254434
